version: '3.9'
services:
  web:
    build: ./app
    command: ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    restart: on-failure
    volumes:
      - ./app:/app
    env_file:
      - ./.env
      - ./.env.db
  postgres:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  celery:
    build: ./app
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./app:/app
    env_file:
      - ./.env
  celery-beat:
    build: ./app
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./app:/app
    env_file:
      - ./.env
volumes:
  redisdata:
  postgres_data: