# Generated by Django 3.2.10 on 2022-01-04 15:49

import apps.client.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220103_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[apps.client.validator.is_valid_iran_code]),
        ),
    ]
