# Generated by Django 3.2.10 on 2022-01-06 09:12

import apps.client.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(default='', max_length=11, validators=[apps.client.validator.is_valid_mobile_number]),
            preserve_default=False,
        ),
    ]
