# Generated by Django 3.2.10 on 2022-01-06 09:13

import apps.client.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, validators=[apps.client.validator.is_valid_mobile_number]),
        ),
    ]
