# Generated by Django 3.2.10 on 2022-01-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='account', to='credit.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source', to='credit.account'),
        ),
    ]
