# Generated by Django 3.2.9 on 2022-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_alter_account_daily_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Profit', 'Profit')], max_length=10),
        ),
    ]
