# Generated by Django 3.2.9 on 2022-01-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0002_alter_loan_total_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
