# Generated by Django 3.2.9 on 2022-01-07 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20220107_1414'),
        ('debit', '0003_alter_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client.client'),
        ),
    ]
