# Generated by Django 3.2.10 on 2022-01-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_debit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_loan',
        ),
    ]
