# Generated by Django 3.2.9 on 2022-01-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(20000000)]),
        ),
        migrations.AddField(
            model_name='client',
            name='total_debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AddField(
            model_name='client',
            name='total_loan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
