# Generated by Django 3.2.10 on 2022-01-03 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_auto_20220103_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)])),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=20)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], max_length=10)),
                ('source', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(-10000000), django.core.validators.MaxValueValidator(10000000)])),
                ('creat_date_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='credit.account')),
            ],
        ),
    ]
