# Generated by Django 3.2.10 on 2022-01-06 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_account_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
